$(function() {
	var ref = new Firebase('https://epiclines.firebaseio.com/');
	var convosRef = ref.child("convos");
	// var convo = convosRef.push({
	// 	author: "Juan",
	// 	context: "You just met",
	// 	upvotes: 30,
	// 	downvotes: 4
	// });
	// var convoRef = convosRef.child(convo.key());
	// convoRef.push({
	// 	you: true,
	// 	text: "Hey! what's up?"
	// });

	// var line1 = ref.child("line1");
	// line1.on("value",function(snapshot){
	// 	var html="";
	// 	html += "<div id='"+line1.key()+"'>";
	// 	html += "<p>"+snapshot.val().text+"</p>";
	// 	html += '<button id="upvote" type="button" class="btn btn-success">Up</button>';
	// 	html += '<button id="upvote" type="button" class="btn btn-danger">Down</button>';
	// 	html += "</div>";
	// 	$("#mainContainer").append(html);
	// });

	// var newPostRef = postsRef.push();
	// newPostRef.set({
	// 	author: "gracehop",
	// 	title: "Announcing COBOL, a New Programming Language"
	// 	});  // we can also chain the two calls together
	// postsRef.push().set({
	// 	author: "alanisawesome",
	// 	title: "The Turing Machine"
	// });
	// postsRef.push({
	// 	author: "gracehop",
	// 	title: "Announcing COBOL, a New Programming Language"
	// });


		// var newPostRef = postsRef.push();// Generate a reference to a new location and add some data using push()
		// var postID = newPostRef.key();// Get the unique ID generated by push()
		//alert(myDataRef.child('lines').val());
		// myDataRef.push({name: name, text: text});
		// myFirebaseRef.set({
		// 	title: "Hello World!",
		// 	author: "Firebase",
		// 	location: {
		// 		city: "San Francisco",
		// 		state: "California",
		// 		zip: 94103
		// 	}
		// });
		// myFirebaseRef.child("location/city").on("value", function(snapshot) {
		// 	alert(snapshot.val()); 
		// });

	});
